import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../../style/globals.css";
import { dir } from "i18next";

// These come from [locale] route param
export async function generateStaticParams() {
  return [{ locale: "en" }, { locale: "ar" }];
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({ children, params }: RootLayoutProps) {
  const htmlDir = dir(params.locale); // 'ltr' or 'rtl'

  return (
    <html lang={params?.locale || "ar"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0`}
      >
        <div className="w-full m-0 p-0 overflow-x-hidden">{children}</div>
      </body>
    </html>
  );
}
